// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `plt_message_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.juzix.plt.slice.message;

/**
 * 消息服务
 **/
public interface PltMessageService extends Ice.Object,
                                           _PltMessageServiceOperations, _PltMessageServiceOperationsNC
{
    public static final String ice_staticId = "::message::PltMessageService";

    public static final long serialVersionUID = 60160264L;
}
