// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `plt_proxy_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.juzix.plt.slice.proxy;

/**
 * 业务代理服务
 **/
public interface _PltProxyServiceOperationsNC
{
    /**
     * 业务代理(客户端)
     * @param __cb The callback object for the operation.
     **/
    void invoke_async(AMD_PltProxyService_invoke __cb, PltInvokeReq req)
        throws com.juzix.plt.slice.common.PltException;
}
