// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `plt_exception_biz.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.juzix.plt.slice.proxy;

/**
 * 业务系统登陆(客户端)
 **/

public abstract class Callback_PltBizUserService_loginForBiz
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1UE<com.juzix.plt.slice.proxy.PltLoginBizResp>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        PltBizUserServicePrxHelper.__loginForBiz_completed(this, __result);
    }
}
