// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `plt_glacier2_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.juzix.plt.slice.session;

/**
 * 客户端的消息回调对象
 **/
public interface PltMsgCallback extends Ice.Object,
                                        _PltMsgCallbackOperations, _PltMsgCallbackOperationsNC
{
    public static final String ice_staticId = "::session::PltMsgCallback";

    public static final long serialVersionUID = 298456507L;
}
