// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `plt_glacier2_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.juzix.plt.slice.session;

/**
 * 会话服务
 **/
public interface PltSession extends Ice.Object,
                                    _PltSessionOperations, _PltSessionOperationsNC,
                                    Glacier2.Session
{
    public static final String ice_staticId = "::session::PltSession";

    public static final long serialVersionUID = 2024442766L;
}
