// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `plt_user_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.juzix.plt.slice.user;

/**
 * 查询用户会话信息
 **/

public abstract class Callback_PltUserService_queryUserInfo
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1UE<com.juzix.plt.slice.user.PltUserInfo>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        PltUserServicePrxHelper.__queryUserInfo_completed(this, __result);
    }
}
