// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `plt_user_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.juzix.plt.slice.user;

public final class PltUserServicePrxHolder
{
    public
    PltUserServicePrxHolder()
    {
    }

    public
    PltUserServicePrxHolder(PltUserServicePrx value)
    {
        this.value = value;
    }

    public PltUserServicePrx value;
}
