// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `plt_user_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.juzix.plt.slice.user;

/**
 * 用户服务
 **/
public interface PltUserService extends Ice.Object,
                                        _PltUserServiceOperations, _PltUserServiceOperationsNC
{
    public static final String ice_staticId = "::user::PltUserService";

    public static final long serialVersionUID = 1805133160L;
}
