// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `plt_file_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.juzix.plt.slice.file;

/**
 * 大文件上传结束上传任务
 **/

public abstract class Callback_PltFileService_endUpTask
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1UE<String>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        PltFileServicePrxHelper.__endUpTask_completed(this, __result);
    }
}
