// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `plt_file_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.juzix.plt.slice.file;

public enum PltEndType implements java.io.Serializable
{
    
    Commit(0),
    
    Cancel(1);

    public int
    value()
    {
        return __value;
    }

    public static PltEndType
    valueOf(int __v)
    {
        switch(__v)
        {
        case 0:
            return Commit;
        case 1:
            return Cancel;
        }
        return null;
    }

    private
    PltEndType(int __v)
    {
        __value = __v;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeEnum(value(), 1);
    }

    public static void
    __write(IceInternal.BasicStream __os, PltEndType __v)
    {
        if(__v == null)
        {
            __os.writeEnum(com.juzix.plt.slice.file.PltEndType.Commit.value(), 1);
        }
        else
        {
            __os.writeEnum(__v.value(), 1);
        }
    }

    public static PltEndType
    __read(IceInternal.BasicStream __is)
    {
        int __v = __is.readEnum(1);
        return __validate(__v);
    }

    private static PltEndType
    __validate(int __v)
    {
        final PltEndType __e = valueOf(__v);
        if(__e == null)
        {
            throw new Ice.MarshalException("enumerator value " + __v + " is out of range");
        }
        return __e;
    }

    private final int __value;
}
