// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `plt_file_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.juzix.plt.slice.file;

/**
 * 文件服务
 **/
public interface PltFileService extends Ice.Object,
                                        _PltFileServiceOperations, _PltFileServiceOperationsNC
{
    public static final String ice_staticId = "::file::PltFileService";

    public static final long serialVersionUID = 2084791944L;
}
