// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `plt_file_service.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.juzix.plt.slice.file;

/**
 * 文件下载请求参数
 **/
public class PltFileDownReq implements java.lang.Cloneable, java.io.Serializable
{
    /**
     * 文件id
     **/
    public String fileId;

    /**
     * 文件id
     **/
    public String
    getFileId()
    {
        return fileId;
    }

    /**
     * 文件id
     **/
    public void
    setFileId(String _fileId)
    {
        fileId = _fileId;
    }

    /**
     * 开始字节数
     **/
    public int startBytes;

    /**
     * 开始字节数
     **/
    public int
    getStartBytes()
    {
        return startBytes;
    }

    /**
     * 开始字节数
     **/
    public void
    setStartBytes(int _startBytes)
    {
        startBytes = _startBytes;
    }

    /**
     * 结束字节数
     **/
    public int endBytes;

    /**
     * 结束字节数
     **/
    public int
    getEndBytes()
    {
        return endBytes;
    }

    /**
     * 结束字节数
     **/
    public void
    setEndBytes(int _endBytes)
    {
        endBytes = _endBytes;
    }

    public PltFileDownReq()
    {
        fileId = "";
    }

    public PltFileDownReq(String fileId, int startBytes, int endBytes)
    {
        this.fileId = fileId;
        this.startBytes = startBytes;
        this.endBytes = endBytes;
    }

    public boolean
    equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        PltFileDownReq _r = null;
        if(rhs instanceof PltFileDownReq)
        {
            _r = (PltFileDownReq)rhs;
        }

        if(_r != null)
        {
            if(fileId != _r.fileId)
            {
                if(fileId == null || _r.fileId == null || !fileId.equals(_r.fileId))
                {
                    return false;
                }
            }
            if(startBytes != _r.startBytes)
            {
                return false;
            }
            if(endBytes != _r.endBytes)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int
    hashCode()
    {
        int __h = 5381;
        __h = IceInternal.HashUtil.hashAdd(__h, "::file::PltFileDownReq");
        __h = IceInternal.HashUtil.hashAdd(__h, fileId);
        __h = IceInternal.HashUtil.hashAdd(__h, startBytes);
        __h = IceInternal.HashUtil.hashAdd(__h, endBytes);
        return __h;
    }

    public PltFileDownReq
    clone()
    {
        PltFileDownReq c = null;
        try
        {
            c = (PltFileDownReq)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void
    __write(IceInternal.BasicStream __os)
    {
        __os.writeString(fileId);
        __os.writeInt(startBytes);
        __os.writeInt(endBytes);
    }

    public void
    __read(IceInternal.BasicStream __is)
    {
        fileId = __is.readString();
        startBytes = __is.readInt();
        endBytes = __is.readInt();
    }

    static public void
    __write(IceInternal.BasicStream __os, PltFileDownReq __v)
    {
        if(__v == null)
        {
            __nullMarshalValue.__write(__os);
        }
        else
        {
            __v.__write(__os);
        }
    }

    static public PltFileDownReq
    __read(IceInternal.BasicStream __is, PltFileDownReq __v)
    {
        if(__v == null)
        {
             __v = new PltFileDownReq();
        }
        __v.__read(__is);
        return __v;
    }
    
    private static final PltFileDownReq __nullMarshalValue = new PltFileDownReq();

    public static final long serialVersionUID = 279097780L;
}
