// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `plt_exception.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.juzix.plt.slice.common;

public class PltException extends Ice.UserException
{
    public PltException()
    {
        errorMsg = "";
    }

    public PltException(Throwable __cause)
    {
        super(__cause);
        errorMsg = "";
    }

    public PltException(int errorCode, String errorMsg)
    {
        this.errorCode = errorCode;
        this.errorMsg = errorMsg;
    }

    public PltException(int errorCode, String errorMsg, Throwable __cause)
    {
        super(__cause);
        this.errorCode = errorCode;
        this.errorMsg = errorMsg;
    }

    public String
    ice_name()
    {
        return "common::PltException";
    }

    public int errorCode;

    public String errorMsg;

    protected void
    __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice("::common::PltException", -1, true);
        __os.writeInt(errorCode);
        __os.writeString(errorMsg);
        __os.endWriteSlice();
    }

    protected void
    __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        errorCode = __is.readInt();
        errorMsg = __is.readString();
        __is.endReadSlice();
    }

    public static final long serialVersionUID = -1988900371L;
}
